version: '3.4'

services:
  gamehavenmain:
    image: jorritdeschaux/gamehaven:latest
    ports:
        - "5000:80"

  gamehavenfront:
    image: jorritdeschaux/gamehaven:front-latest
    ports:
        - "3000:3000"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
       - '3306:3306'
    environment:
       MYSQL_DATABASE: gamehaven
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  pma:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db


volumes:
  dbdata:

    
