version: '3.4'

services:
  gamehavenmain:
    image: ${DOCKER_REGISTRY-}gamehavenmain
    build:
      context: .
      dockerfile: GameHavenMain/Dockerfile
    ports:
        - "5000:5000"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
       - '6603:3306'
    environment:
       MYSQL_ROOT_PASSWORD: helloworld
    volumes:
      - dbdata:/var/lib/mysql

  pma:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db

volumes:
  dbdata:

    
