name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependencies
      run: dotnet restore ./GameHavenMain.sln
        
    - name: Build
      run: dotnet build GameHavenMain/GameHavenMain.csproj --configuration Release
      
    - name: Tests
      run: dotnet test ./GameHavenMain.sln --configuration Release
  
  push-images-to-hub:
  
      runs-on: ubuntu-latest
      steps:
      
      - uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: jorritdeschaux/gamehavenmain
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: Dockerfile
          directory: GameHavenMain/GameHavenMain
          
