name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependencies
      run: dotnet restore ./GameHavenMain.sln
        
    - name: Build
      run: dotnet build GameHavenMain/GameHavenMain.csproj --configuration Release
      
    - name: Tests
      run: dotnet test ./GameHavenMain.sln --configuration Release
  
  push-images-to-hub:
  
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          tags: jorritdeschaux/gamehavenmain:latest
          build-args: PROFILE=nectar,ARG2=test
          
